// This file is automatically generated by qtc from "base.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/base.qtpl:1
package templates

//line templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// This is a template built using https://github.com/kindrid/quicktemplate. Text outside
// function templates is ignored by the template compiler.
//

//line templates/base.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.qtpl:5
type SuiteExport interface {
	//line templates/base.qtpl:5
	Structs() string
	//line templates/base.qtpl:5
	StreamStructs(qw422016 *qt422016.Writer)
	//line templates/base.qtpl:5
	WriteStructs(qq422016 qtio422016.Writer)
//line templates/base.qtpl:5
}

//line templates/base.qtpl:11
func StreamPrintStructs(qw422016 *qt422016.Writer) {
	//line templates/base.qtpl:11
	qw422016.N().S(`
type StructName struct {
    Field string   // a string here
}
`)
//line templates/base.qtpl:15
}

//line templates/base.qtpl:15
func WritePrintStructs(qq422016 qtio422016.Writer) {
	//line templates/base.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/base.qtpl:15
	StreamPrintStructs(qw422016)
	//line templates/base.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:15
}

//line templates/base.qtpl:15
func PrintStructs() string {
	//line templates/base.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/base.qtpl:15
	WritePrintStructs(qb422016)
	//line templates/base.qtpl:15
	qs422016 := string(qb422016.B)
	//line templates/base.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/base.qtpl:15
	return qs422016
//line templates/base.qtpl:15
}

//line templates/base.qtpl:17
func (se *SuiteExport) StreamStructs(qw422016 *qt422016.Writer) {
	//line templates/base.qtpl:17
	qw422016.N().S(`
pretend structs here
`)
//line templates/base.qtpl:19
}

//line templates/base.qtpl:19
func (se *SuiteExport) WriteStructs(qq422016 qtio422016.Writer) {
	//line templates/base.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/base.qtpl:19
	se.StreamStructs(qw422016)
	//line templates/base.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:19
}

//line templates/base.qtpl:19
func (se *SuiteExport) Structs() string {
	//line templates/base.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/base.qtpl:19
	se.WriteStructs(qb422016)
	//line templates/base.qtpl:19
	qs422016 := string(qb422016.B)
	//line templates/base.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/base.qtpl:19
	return qs422016
//line templates/base.qtpl:19
}
