// This file is automatically generated by qtc from "golang.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/golang.qtpl:1
package templates

//line templates/golang.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// This is a template built using https://github.com/kindrid/quicktemplate. Text outside
// function templates is ignored by the template compiler.
//

//line templates/golang.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)
